package com.app.integration.inbound.constant

object IntegrationConstant{
  val URL_SOURCE_INTERNAL_PROJECTID = "sointprjid"
  val URL_SOURCE_EXTERNAL_PROJECTID = "soextprjid"
  val URL_SOURCE_INTERNAL_USERID = "sointusrid"
  val URL_SOURCE_EXTERNAL_USERID = "soexturid"

  val SWIFTENTERPRISE = "SE"
  val SWIFTKANBAN = "SK"
  val SWIFTEASE = "EASe"

  val SWIFTENTERPRISE_SUPPORT = "SwiftEnterprise"
  val SWIFTKANBAN_SUPPORT = "KanbanSupport"
  val SWIFTEASE_SUPPORT = "EASeSupport"

  val METHOD_GET = "GET"
  val METHOD_POST = "POST"
  val METHOD_PUT = "PUT"
  val METHOD_DELETE = "DELETE"
  val CONTENTTYPE_APPLICATION_JSON = "application/json"
  val CONTENTTYPE_APPLICATION_FORMURLENCODED = "application/x-www-form-urlencoded"
  val  CONTENTTYPE_APPLICATION_TEXT = "text/plain"
  val MAIL_SUBJECT = "subject"
  val MAIL_BODY = "body"
  val MAIL_TO = "to"

  val SWIFTENTERPRISE_REST_TOKEN_URL = "/api/TokenService/getToken"
  val SWIFTENTERPRISE_REST_TOKEN_LOGINID = "Loginid"
  val SWIFTENTERPRISE_REST_TOKEN_PASSWORD = "Password"
  val SWIFTENTERPRISE_REST_AUTHORIZATION_KEY = "AuthorizationToken"
  val SWIFTENTERPRISE_REST_TOKEN_DATA = "data"

  val SWIFTENTERPRISE_REST_USER_DETAILS_URL = "/api/UserService/GetUserDetails/"
  val SWIFTENTERPRISE_REST_PROJECT_DETAILS_URL = "/api/ProjectService/getProjectDetails/"

  val SWIFTKANBAN_REST_CARDTYPE_DETAILS_URL = "/metadata-operations/boards/"
  val SWIFTKANBAN_REST_CARD_FIELDS_LIST_URL = "/metadata-operations/items/"
  val SWIFTKANBAN_REST_USER_DETAILS_URL = "/user-operations/users/"
  val SWIFTKANBAN_REST_PROJECT_DETAILS_URL = "/board-operations/boards/"
  val SWIFTKANBAN_REST_IFORM_DETAILS_URL = "/card-operations/boards/"
  val SWIFTKANBAN_REST_TOKEN_URL = "/secured/auth"
  val SWIFTKANBAN_PROJECT_LIST_URL = "/board-operations/boards"
  val SWIFTKANBAN_SEND_MAIL_URL = "/messaging-operations/email"

  val SWIFTKANBAN_REST_RESPONSE_KEY_CARDTYPES = "/Response/details/CardTypes/Card"
  val SWIFTKANBAN_REST_RESPONSE_KEY_USER = "/Response/details/userData"
  val SWIFTKANBAN_REST_RESPONSE_KEY_BOARD = "/Response/details/boardDetails"
  val SWIFTKANBAN_CARDS_URL_PATH = "/cards/"
  val SWIFTKANBAN_REST_AUTHENTICATION_TOKEN = "AuthenticationToken"
  val SWIFTKANBAN_REST_AUTHENTICATION_KEYWORD = "SwiftKanban"
  val SWIFTKANBAN_REST_AUTHORIZATION_KEY = "AuthorizationToken"
  val SWIFTKANBAN_REST_TOKEN_DATA = "authDetails"
  val SWIFTKANBAN_USER_STATUS_ACTIVE = "Active"

  val SWIFTENTERPRISE_REST_ALL_CARD_DETAILS_URL = "/api/EFormService/getEFormDetailsDefinitionForOwner/"
  val SWIFTENTERPRISE_OWNERTYPE_PROJECT = "Prj"
  val SWIFTENTERPRISE_REST_EFORM_LIST_URL = "/api/EFormService/getEFormItemListWithFilter/"
  val SWIFTENTERPRISE_REST_EFORM_DETAILS_URL = "/api/EFormService/getEFormItemDetails/"
  val SWIFTENTERPRISE_DEFAULT_TIMESTAMP = "01-Jan-1970 00:00:00"

  val SWIFTENTERPRISE_REST_EFORM_CREATE_DETAILS_URL = "/api/EFormService/createEFormItemData/"
  val SWIFTENTERPRISE_REST_CUSTOM_FIELD_URL = "/api/EFormService/getEFormDefinition/"



  val SWIFTENTERPRISE_FIELD_LABELS = "FieldLabels"
  val SWIFTENTERPRISE_FIELD_VALUES = "FieldValues"
  val SWIFTENTERPRISE_CREATOR_LOGINID = "CreatorLoginId"
  val SWIFTENTERPRISE_OWNERTYPE = "OwnerType"
  val SWIFTENTERPRISE_OWNERCODE = "OwnerCode"
  val SWIFTENTERPRISE_OWNERID = "OwnerId"
  val SWIFTENTERPRISE_ITEMTYPE = "ItemType"

  val SWIFTENTERPRISE_EFORM_NAME = "Name"
  val SWIFTENTERPRISE_EFORM_DESCRIPTION = "Description"
  val SWIFTENTERPRISE_ESCAPE_COMMA = "ESCAPECOMMA"
  val SWIFTENTERPRISE_EFORM_ITEMCODE = "ItemCode"

  val SWIFTKANBAN_IFORM_NAME = "name"
  val SWIFTKANBAN_IFORM_NAME_LABEL = "Name"
  val SWIFTKANBAN_IFORM_DESCRIPTION = "description"
  val SWIFTKANBAN_IFORM_DESCRIPTION_LABEL = "Description"
  val SWIFTKANBAN_IFORM_SOURCE = "source"
  val SWIFTKANBAN_ESCAPE_COMMA = "ESCAPECOMMA"
  val SWIFTKANBAN_IFORM_ITEMCODE = "id"
  val SWIFTKANBAN_IFORM_ITEMTYPE = "workType"
  val SWIFTKANBAN_EXT_CARDID_RESPONSE = "ExternalCardId"
  val SWIFTKANBAN_CARD_UNIQUEID = "cardUniqueId"
  val SWIFTKANBAN_IFORM_CARDTYPE = "cardType"
  val SWIFTKANBAN_PROJECTID = "projectId"
  val SWIFTKANBAN_BOARDID = "boardId"

  val SWIFTENTERPRISE_ITEMID = "ItemId"
  val SWIFTENTERPRISE_AUDITLOGCOMMENTS = "AuditLogComments"
  val SWIFTENTERPRISE_COMMENTS = "Comments"
  val SWIFTENTERPRISE_LOGGEDBY = "LoggedBy"
  val SWIFTENTERPRISE_LABEL_INFO = "/LabelInfo"
  val SWIFTENTERPRISE_ITEMS = "/Items"
  val SWIFTENTERPRISE_ITEM = "/Item"


  val SWIFTENTERPRISE_REST_ADD_ACTIVITYLOG_URL = "/api/EFormService/addActivityLog"
  val SWIFTENTERPRISE_REST_ADD_ATTACHMENT_URL = "/api/EFormService/AddAttachment"
  val SWIFTENTERPRISE_REST_ADD_COMMENTS_URL = "/api/EFormService/addComments"
  val SWIFTENTERPRISE_PROJECT_LIST_URL = "/api/ProjectService/getProjectListFromLoginId/"
  val SWIFTENTERPRISE_SEND_MAIL_URL = "/api/EmailService/sendMail"

  val SWIFTENTERPRISE_ATTACHMENT_LOGINID = "LoginId"
  val SWIFTENTERPRISE_ATTACHMENT_FILENAME = "AttachmentFileName"
  val SWIFTENTERPRISE_ATTACHMENT_BYTE = "AttachmentByte"

  val ISSUE_COLLECTOR_REST_EFORM_UPDATE_CALL = "ISSUE_COLLECTOR_REST_EFORM_UPDATE_CALL"

  val SWIFTENTERPRISE_ATTACHMENT_DESCRIPTION = "Description"

  val SWIFTKANBAN_ISSUE_COLLECTOR_LABEL = "IssueCollector"
  val SWIFTKANBAN_REST_ADD_ATTACHMENT_URL = "/attachment-operations/boards/"
  val SWIFTKANBAN_REST_COMMENTS_CREATE_URL = "/comment-operations/boards/"
  val SWIFTKANBAN_ATTACHMENT_LOGINID = "attachmentAddedBy"
  val SWIFTKANBAN_ATTACHMENT_FILENAME = "fileNameWithExt"
  val SWIFTKANBAN_ATTACHMENT_BYTE = "content"
  val SWIFTKANBAN_PROJECT_CLOSED_STATUS = "Closed"

  val SWIFTENTERPRISE_CONTROL_TYPE_TEXT = "Text"
  val SWIFTENTERPRISE_CONTROL_TYPE_COMBO = "Combo"
  val SWIFTENTERPRISE_CONTROL_TYPE_CHECKBOX = "CheckBox"
  val SWIFTENTERPRISE_CONTROL_TYPE_TEXTAREA = "TextArea"
  val SWIFTENTERPRISE_CONTROL_TYPE_RICHTEXT = "RText"
  val SWIFTENTERPRISE_CONTROL_TYPE_RADIOBUTTON = "RadioButton"

  val SE_FIELD_DATA_TYPE_STRING = "String"
  val SE_FIELD_DATA_TYPE_DCK = "Dynaic Content Key"
  val SE_FIELD_DATA_TYPE_DATE = "Date"
  val SE_FIELD_DATA_TYPE_NUMBER = "Number"

  val SK_FIELD_DATA_TYPE_STRING = "String"
  val SK_FIELD_DATA_TYPE_LONG = "Long"
  val SK_FIELD_DATA_TYPE_DOUBLE = "Double"
  val SK_FIELD_DATA_TYPE_BOOLEAN = "Boolean"
  val SK_FIELD_DATA_TYPE_DATE = "Date"

  val FIELD_DATA_TYPE_STRING = "string"
  val FIELD_DATA_TYPE_NUMBER = "number"
  val FIELD_DATA_TYPE_DATE = "Date"

  val SWIFTKANBAN_FIELD_TYPE_REGULAR_TEXT = "Regular Text"
  val SWIFTKANBAN_FIELD_TYPE_SINGLELINE_TEXT = "Single-Line Text"
  val SWIFTKANBAN_FIELD_TYPE_SINGLELINE_WITH_SPACE = "Single - Line Text"
  val SWIFTKANBAN_FIELD_TYPE_MULTILINE_TEXT = "Multi-Line Text"
  val SWIFTKANBAN_FIELD_TYPE_INTEGER = "Integer"
  val SWIFTKANBAN_FIELD_TYPE_DECIMAL = "Decimal"
  val SWIFTKANBAN_FIELD_TYPE_BOOLEAN = "Boolean"
  val SWIFTKANBAN_FIELD_TYPE_DATE = "Date"

  val SWIFTKANBAN_INPUT_TYPE_REGULAR_MANUAL_ENTRY = "Manual Entry"
  val SWIFTKANBAN_INPUT_TYPE_REGULAR_STATIC_LIST = "Static List"
  val SWIFTKANBAN_INPUT_TYPE_DYNAMIC_LIST = "Dynamic List"

  val SWIFTKANBAN_NO = "NO"
  val SWIFTKANBAN_YES = "Yes"
  val SWIFTKANBAN_LIST_ITEM_STATUS_ACTIVE = "Active"

  val SWIFTKANBAN_COMMENT_TEXT = "commentText"
  val SWIFTKANBAN_COMMENTS_BY = "commentedBy"
  val SWIFTKANBAN_REQ_BODY_COMMENT = "comment"
  val SWIFTKANBAN_STORY_MAPPING_REST_CARDCODE_FILTER = ":"
  val HEADER_SOURCE_KEY = "source"
  val APPLICATION_LABEL = "External Work Request"

  val SWIFTENTERPRISE_FACTORYSHIP_SUPPORTED_EFORMS: List[String] = List("Aci", "ADHW", "ABUG", "Dft", "Doc", "Siu", "Min", "Rsk", "SwReq", "ATST", "UsrReq", "AUSRST")

  val SWIFTENTERPRISE_ISSUE_COLLECTOR_FILE_NAME = "ISSUE_COLLECTOR_FILE_NAME"
}